services:
  db:
    image: mariadb:10.1
    environment:
      MYSQL_ROOT_PASSWORD: [your_password]
      MYSQL_USER: [username]
      MYSQL_PASSWORD: [your_password]
      MYSQL_DATABASE: [db-name]
    volumes:
      - '/filerun/db:/var/lib/mysql'
  web:
    image: 'filerun/filerun:8.1'
    environment:
      FR_DB_HOST: db
      FR_DB_PORT: 3306
      FR_DB_NAME: [db-name]
      FR_DB_USER: [username]
      FR_DB_PASS: [your_password]
      APACHE_RUN_USER: www-data
      APACHE_RUN_USER_ID: 33
      APACHE_RUN_GROUP: www-data
      APACHE_RUN_GROUP_ID: 33
    depends_on:
      - db
    links:
      - 'db:db'
    ports:
      - '[port]:80'
    volumes:
      - '/filerun/html:/var/www/html'
      - '/filerun/user-files:/user-files'
